services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - gradle_cache:/home/gradle/.gradle
    ports:
      - '40888:8888'
    environment:
      - MONGODB_URI=mongodb://root:password@lunar-mongo/lunarclient?authSource=admin
      - REDIS_URL=redis://lunar-redis:6379/0
      - RABBITMQ_HOST=lunar-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_STREAM_PORT=5552
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VIRTUAL_HOST=lunar
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: always

  mongo:
    image: mongo:latest
    container_name: lunar-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=lunarclient
    volumes:
      - mongo:/data/db
    restart: always

  redis:
    image: redis:latest
    container_name: lunar-redis
    restart: always

  rabbitmq:
    image: rabbitmq:4.1.0-beta.4-management-alpine
    container_name: lunar-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: lunar
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

configs:
  plugins:
    content: "[rabbitmq_management, rabbitmq_stream]."

volumes:
  mongo:
    driver: local
  rabbitmq_data:
    driver: local
  gradle_cache:
    driver: local
