services:
  mongo:
    image: mongo:latest
    container_name: lunar-mongo
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_DATABASE=lunarclient'
    volumes:
      - mongo:/data/db
    restart: no

  valkey:
    image: valkey/valkey:latest
    container_name: lunar-valkey
    ports:
      - '6379:6379'
    restart: no

#  minio:
#    image: minio/minio:latest
#    container_name: lunar-minio
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      - MINIO_ACCESS_KEY=minio
#      - MINIO_SECRET_KEY=minio123
#    volumes:
#      - minio_data:/data
#    command: server /data --console-address ":9001"
#    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: lunar-zookeeper
    restart: no
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: lunar-kafka
    hostname: kafka
    depends_on:
      - zookeeper
    restart: no
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092,PLAINTEXT_HOST1://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_HOST1:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: lunar-schema-registry
    depends_on:
      - kafka
    restart: no
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29093'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

volumes:
  mongo:
    driver: local
#  minio_data:
#    driver: local
