services:
  api:
    container_name: lunar-api
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ~/.gradle:/root/.gradle
    ports:
      - '40888:8080'
    environment:
      - MONGODB_URI=mongodb://root:password@lunar-mongo/lunarclient?authSource=admin
      - REDIS_URL=redis://lunar-redis:6379/0
      - API_TOKEN=api_token
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    depends_on:
      - mongo
      - redis
    restart: always

  mongo:
    image: mongo:latest
    container_name: lunar-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=lunarclient
    volumes:
      - mongo:/data/db
    restart: always

  redis:
    image: redis:latest
    container_name: lunar-redis
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: qbychat-zookeeper
    restart: always
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: lunar-kafka
    hostname: kafka
    depends_on:
      - zookeeper
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: lunar-schema-registry
    depends_on:
      - kafka
    restart: always
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

volumes:
  mongo:
    driver: local
  gradle_cache:
    driver: local
