spring:
  application:
    name: lunar-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:password@localhost/lunarclient?authSource=admin}
    redis:
      url: ${REDIS_URL:redis://127.0.0.1:6379/0}
  security:
    jwt:
      key: ${JWT_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
      expire: ${JWT_EXPIRE:1}
  cloud:
    stream:
      bindings:
        lunarWebsocketPayloadConsumer-in-0:
          destination: lunar-1
      kafka:
        bindings:
          supplier-out-0:
            producer:
              configuration:
                schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs

instance:
  # Used to recognize instances in Kubernetes
  id: ${HOSTNAME:earthsworth}

lunar:
  user:
    # Check if the player is authenticated with a valid Mojang/Microsoft account.
    verify: true
    # Default roles
    # They will automatically receive roles when joining the server.
    roleAssignments:
      # CubeWhy
      - uuid: ee0d0448-641e-405a-96ba-242c92845d85
        roles:
          - ADMIN
      # USTC
      - uuid: a04d619a-2e75-41b7-b510-1da91ef001c4
        roles:
          - ADMIN
  friend:
    bot:
      enabled: ${LUNAR_BOT_ENABLED:true}
      username: ${LUNAR_BOT_USERNAME:lunar_bot}
    # max friends
    max: 200
  sentry:
    filters:
      - identifier: everything
        regex: ".*"
  upload:
    maxSize: 5mb
  discord:
    enabled: false
    token: discord_token
    irc:
      # Channel ID to sync irc messages
      channel: 1358028995899293746
  alert:
    show: true
    name: Discord
    text: Join our Discord today!
    color: RED
    icon: BULLHORN
    dismissable: true
    link: https://discord.lunarclient.top