server:
  port: 8888

spring:
  application:
    name: lunar-api
  data:
    mongodb:
      uri: mongodb://root:password@localhost/lunarclient?authSource=admin
    redis:
      url: redis://127.0.0.1:6379/0
  security:
    jwt:
      key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      # How long will the jwt expire (unit: day)
      expire: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    virtual-host: lunar
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true


lunar:
  user:
    default:
      # Default user details
      username: admin
      password: password
  friend:
    # Add a bot to user's friend list that users can use commands
    bot:
      enabled: true
      username: lunar_bot
    # max number have friend
    max: 50