{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-api.fullname" . }}-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      enableServiceLinks: false
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.9.0
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: '{{ include "lunar-api.fullname" . }}-kafka-bootstrap:9092'
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar-api.fullname" . }}-schema-registry
spec:
  selector:
    app: {{ include "lunar-api.fullname" . }}-schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: schema-registry
{{- end }}